FingerprintRecognition/FingerprintRecognition/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from manageData import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.homepage, name="homepage"),
    
      
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='home.html'), name='logout'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('train/', views.train, name='train'),
    path('choose_employee/', views.choose_employee, name='choose-employee'),
    path('show_sample/<employee_id', views.show_sample_employee, name='show-sample-employee'),
    path('view_statitics_home', views.view_statitics_home, name='view-statitics-home'),


    path('all_employees/', views.all_employee, name = 'list-employees'),
    path('register/', views.registryNewEml, name='register'),
    path('update_employee/<employee_id>', views.update_employee, name='update-employee'),
    path('delete_employee/<employee_id>', views.delete_employee, name='delete-employee'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FingerprintRecognition/manageData/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
   
    name = models.CharField('Employee Name',null=False,max_length=255)
    dob = models.DateField('Date Of Birth')
    sample = models.IntegerField('Number of Sample', default=0, editable=False)
    def __str__(self) :
        return f"{self.name}"
class Image(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="training_data", editable=True)
    
    def __str__(self) :
        return f"{self.employee} - {self.image.url}"
   

FingerprintRecognition/manageData/forms.py
from django import forms
from django.forms import *

from FingerprintRecognition.settings import DJANGO_LEDGER_FORM_INPUT_CLASSES
from django.utils.translation import gettext_lazy as _
from .models import Employee, Image
# Create your forms here.


# class FengyuanChenDatePickerInput(DateInput):
#     template_name = 'widgets/fengyuanchen_datepicker.html'
class NewEmployeeForm(ModelForm):
	class Meta :
		model = Employee
		fields = ['name', 'dob']
		widgets = {
		'name' : TextInput(attrs= {'class' : 'form-control',
                     'placeholder': _('Employee Name')}),
		'dob' : DateInput(attrs= {'class' : 'form-control', 
                           'placeholder': _('Date of Birtd (YYYY-MM-DD)')}),
		}
	# def clean(self):
	# 	super(NewStudentForm, self).clean()
	# 	name = self.cleaned_data['name']
	# 	dob = self.cleaned_data['dob']
	# 	inClass = self.cleaned_data['inCla']
	# 	if 
		
class chooseEmployeetForm(forms.Form):
    employee_id = IntegerField()

class showSampleForm(ModelForm):
    class Meta:
        model = Image
        fields = ['employee']
        labels = {'employee' : '',}

class ImageForm(ModelForm):
    image = ImageField(
		label="Image",
		widget= ClearableFileInput(attrs={"multiple" : True})
	)

FingerprintRecognition/manageData/views.py
import os, shutil
import shutil
from time import localtime, strftime
from tkinter import filedialog, messagebox
from django.shortcuts import  render, redirect

from .models import Employee, Image
from .forms import NewEmployeeForm, chooseEmployeetForm, showSampleForm, ImageForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, precision_score,recall_score, confusion_matrix
from sklearn.model_selection import StratifiedKFold
from PIL import Image as ImagePIL
import random
import tensorflow as tf
from tensorflow import keras
from keras import layers
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
import os
import shutil
from PIL import ImageFile

####### Khai bao bien de train data
ImageFile.LOAD_TRUNCATED_IMAGES = True
ImagePIL.MAX_IMAGE_PIXELS = 1000000000
config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
root_path = ''
datasetFolderName = root_path+'data'
sourceFiles = []
MODEL_FILENAME=root_path+"model_cv.h5"
classLabels = []
path = 'data/train'
for _, dirnames, filenames in os.walk(path):
    classLabels=dirnames
    break
img_rows, img_cols = 100, 100
train_path=datasetFolderName+'/train/'
test_path=datasetFolderName+'/test/'
validation_path=datasetFolderName+'/validation/'
batch_size = 12
epoch=2
activationFunction='elu'

#--------------------

def homepage(request):
    return render(request, 'home.html')

@login_required
def all_employee(request):
    employee_list = Employee.objects.all()
    return render(request, 'list_employees.html',
                  {'employee_list' : employee_list})

@login_required
def dashboard(request):
    return render(request, 'dashboard.html' )

@login_required
def registryNewEml(request):
	if request.method=='POST':
		form = NewEmployeeForm(request.POST)
		if form.is_valid():
			employee = form.save()
			messages.success(request, f"Registration successful !")
			return redirect('list-employees')
		else :
			return render(request, 'register.html', context={"register_form":form})
	
	form = NewEmployeeForm()
	return render(request, 'register.html', context={"register_form":form})

@login_required
def update_employee(request, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    form = NewEmployeeForm(request.POST or None, instance=employee)
    if form.is_valid():
        employee = form.save()
        messages.success(request, f"Registration successful !")
        return redirect('list-employees')
    else : return render(request, 'update_employee.html', {"employee":employee,"form" : form})
    
    

@login_required
def delete_employee(request, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    employee.delete()
    return redirect('list-employees')
    

@login_required
def choose_employee(request):
    if request.method == 'POST':
        form = chooseEmployeetForm(request.POST)
        data = request.POST.copy()
        id= data.get('employee_id')
        print(type(id))
        if Employee.objects.filter(id=id).exists():
            return redirect('show-sample')
        else :
            messages.warning(request, f'No such employee id found. Please register employee first.')
            return redirect('dashboard')
    else :
        form = chooseEmployeetForm()
        return render(request,'choose_employee.html', {'form': form})
        
@login_required
def show_sample(request, employee_id):
    form= ImageForm(request.POST)
    if Image.objects.filter(fk=employee_id).exists():
        images = Image.objects.all(fk=employee_id)
        return render(request,'show_sample.html', { "form" : form, 'employee_id':employee_id})
    return render(request,'show_sample.html', { 'form':form, 'employee_id':employee_id})
    # images = Image.objects.all()
    # form= showSampleForm(request.POST)
    # return render(request,'show_sample.html', { 'images': images})
      
@login_required
def show_sample_employee(request, employee_id):
    images = Image.objects.get(fk=employee_id)
    return render(request, 'show_sample_employee.html',{'images':images})
      
@login_required      
def add_sample(request, employee_id):
    if request.method == 'POST':
        form = ImageForm(request.POST)
        files = request.FILES.getlist("image")
        if form.is_valid():
            e = form.save(commit=False)
            e.save()
            for i in files:
                Image.objects.create(employee=e)
            return redirect('show-sample')
        else:
            messages.error(request, "Import image file")
            return render(request,'add_sample.html', {employee_id:employee_id, 'form':form})
    else :
        form = ImageForm()
        return render(request,'add_sample.html', {employee_id:employee_id, 'form':form})
        

@login_required
def train(request):
    move_data()
    accuracy, precision, recall, f1Score = train_data()
    accuracy, precision, recall, f1Score = round(accuracy, 2), round(precision, 2), round(recall, 2), round(f1Score, 2)  
    messages.success(request, f"Train data successfull! ")
    messages.success(request,  f"Accuracy = {accuracy}" )
    messages.success(request,  f"Precision = {precision}" )
    messages.success(request,  f"Recall = {recall}" )
    messages.success(request,  f"F1-Score = {f1Score}" )
    return render(request,"train.html")
   
    
def get_last_time_train():
    lastTrained = os.path.getmtime('model_cv.h5') 
    modifiedTime = strftime('%Y-%m-%d %H:%M:%S', localtime(lastTrained))  
    return modifiedTime
  
def get_total_employee():
    path = 'data/test/'
    count=0
    for _, dirnames, filenames in os.walk(path):
        count = len(dirnames)
        break
    return count
  
def get_total_sample():
    train_path = "data/train/"
    test_path = "data/test/"

    num=0
    for _, dirnames, filenames in os.walk(train_path):
        num += len(filenames)
    for _, dirnames, filenames in os.walk(test_path):
        num += len(filenames)
    return num    
  
@login_required
def view_statitics_home(request):
    last_time_train = get_last_time_train()
    total_employee = get_total_employee()
    total_sample = get_total_sample()
    return render(request, 'view_statitics_home.html', {'last_time_train': last_time_train, 
                                                       'total_employee' : total_employee, 
                                                       'total_sample' :total_sample})
  

def create_dataset():
    images = Image.objects.all()
    for image in images:
        id = image.employee.id
        if (os.path.exists('data/train/{}'.format(id))==False):
            os.makedirs('data/train/{}'.format(id))
        if (os.path.exists('data/test/{}'.format(id))==False):
            os.makedirs('data/test/{}'.format(id))
        if (os.path.exists('data/validation/{}'.format(id))==False):
            os.makedirs('data/validation/{}'.format(id))
    
def move_data():
    create_dataset()
    old_dir = "/media/training_data/"
    images = Image.objects.all()
    for image in images:
        image.save()
        shutil.copy(image.image.url[1::], f"data/train/{image.employee.id}")

def transferBetweenFolders(source, dest, splitRate): 
    global sourceFiles
    sourceFiles=os.listdir(source)
    if(len(sourceFiles)!=0):
        transferFileNumbers=int(len(sourceFiles)*splitRate)
        transferIndex=random.sample(range(0, len(sourceFiles)), transferFileNumbers)
        for eachIndex in transferIndex:
            shutil.move(source+str(sourceFiles[eachIndex]), dest+str(sourceFiles[eachIndex]))
    else:
        print("No file moved. Source empty!")
        
def transferAllClassBetweenFolders(source, dest, splitRate):
    for label in classLabels:
        transferBetweenFolders(datasetFolderName+'/'+source+'/'+label+'/', 
                               datasetFolderName+'/'+dest+'/'+label+'/', 
                               splitRate)

def my_metrics(y_true, y_pred):
    accuracy=accuracy_score(y_true, y_pred)
    precision=precision_score(y_true, y_pred,average='weighted')
    recall = recall_score(y_true, y_pred,average='weighted')
    f1Score=f1_score(y_true, y_pred, average='weighted') 
    print("Accuracy  : {}".format(accuracy))
    print("Precision : {}".format(precision))
    print("Recall : {}".format(recall))
    print("f1Score : {}".format(f1Score))
    cm=confusion_matrix(y_true, y_pred)
    print(cm)
    return  accuracy,precision, recall, f1Score


def prepareNameWithLabels(folderName, X, Y):
    sourceFiles=os.listdir(datasetFolderName+'/train/'+folderName)
    for val in sourceFiles:
        X.append(val)
        for i in range(len(classLabels)):
          if(folderName==classLabels[i]):
              Y.append(i)
              
#chuan bi data
def preprocess(X, Y):
    transferAllClassBetweenFolders('test', 'train', 1.0)
    transferAllClassBetweenFolders('train', 'test', 0.3)
    for i in range(len(classLabels)):
        prepareNameWithLabels(classLabels[i], X, Y)
  

#Model
# Note that, this model structure is a very basic one. To achieve better performance, you should change the model structure and hyperparameters according to your needs and data.
def getModel():
    model = Sequential()
    model.add(Conv2D(64, (3, 3), padding='same', activation=activationFunction, input_shape=(img_rows, img_cols, 3)))
    model.add(Conv2D(64, (3, 3), activation=activationFunction))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
 
    model.add(Conv2D(32, (3, 3), padding='same', activation=activationFunction))
    model.add(Conv2D(32, (3, 3), activation=activationFunction))
    model.add(MaxPooling2D(pool_size=(2, 2)))

FingerprintRecognition/manageData/templates/choose_employee.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>

	  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

   <style>
    body{
      background: url('{% static "recognition/img/bg_image.png"%}') no-repeat center center fixed;
      background-size: cover;
      
    }
   
   </style>


	
</head>
<body>

<div class="col-lg-12" style="background: rgba(0,0,0,0.6);max-height: 20px ; padding-top:1em;padding-bottom:3em;color:#fff;border-radius:10px;-webkit-box-shadow: 2px 2px 15px 0px rgba(0, 3, 0, 0.7);
-moz-box-shadow:    2px 2px 15px 0px rgba(0, 3, 0, 0.7);
box-shadow:         2px 2px 15px 0px rgba(0, 3, 0, 0.7); margin-left:auto; margin-right: auto; ">

  <a href="{% url 'dashboard' %}"><h5 class="text-left">  Back</h5></a>
</div>

 <div class="col-lg-4" style="background: rgba(0,0,0,0.6);margin-top:150px ; padding-top:1em;padding-bottom:3em;color:#fff;border-radius:10px;-webkit-box-shadow: 2px 2px 15px 0px rgba(0, 3, 0, 0.7);
-moz-box-shadow:    2px 2px 15px 0px rgba(0, 3, 0, 0.7);
box-shadow:         2px 2px 15px 0px rgba(0, 3, 0, 0.7); margin-left:auto; margin-right: auto; ">

<div id="content" class="colM">
        
  <h1>Add image</h1>
  <div id="content-main">
  <form enctype="multipart/form-data" action="" method="post" novalidate><input type="hidden" >
      <div>
        
  <fieldset class="module aligned ">
    <div class="form-row field-employee">
            <div>
                    <label class="required" for="id_employee">Employee:</label>
                    
                        <div class="related-widget-wrapper">
<select name="employee" required id="id_employee">
      



<div class="col-lg-12" style="padding-top: 100px;">
 {% if messages %}
      {% for message in messages%}
      <div class="alert alert-{{message.tags}}" > {{message}}
      </div>
      {%endfor %}

    {%endif%}
  </div>


  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

FingerprintRecognition/manageData/templates/dashboard.html
{% load static %}


<!DOCTYPE html>
<html>
<head>

	  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

   <style>
    body{
      background: url('{% static "recognition/img/bg_image.png"%}') no-repeat center center fixed;
      background-size: cover;
      
    }
   
   </style>

<script  type='text/javascript'
src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'>
$(document).ready(function(){
  $("#train").click(function(){
    alert("Training begun. This may take upto 5 minutes. Please wait.");
  });
});
</script>
	
</head>
<body>
   <div class="col-lg-12" style="background: rgba(0,0,0,0.6);margin-top:3em;margin-bottom:5em;padding-top:1em;padding-bottom:3em;color:#fff;border-radius:10px;-webkit-box-shadow: 2px 2px 15px 0px rgba(0, 3, 0, 0.7);
-moz-box-shadow:    2px 2px 15px 0px rgba(0, 3, 0, 0.7);
box-shadow:         2px 2px 15px 0px rgba(0, 3, 0, 0.7);">
    <div class="col-sm-12">
       <a href="{% url 'logout' %}"><h5 class="text-right"><i class="fa fa-user-circle" aria-hidden="true"></i> Logout</h5></a>
      <h1 class="text-center section-title" style="margin-bottom:2em">Welcome,admin.</h1>
    </div>
     <style>
      h4{
        margin-bottom: 1.5em;
        padding-top: 30px;

      }
      img{
        border-radius:50%;
        -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
     transition: all 0.3s ease-in-out;
      }
      img:hover{
        -webkit-box-shadow: 2px 2px 21px 0px rgba(0, 3, 0, 0.91);
        -moz-box-shadow:    2px 2px 21px 0px rgba(0, 3, 0, 0.91);
        box-shadow:         2px 2px 21px 0px rgba(0, 3, 0, 0.91);
        border:2px solid #fff;
      }
      h3{
        margin-bottom: 1.3em;
      }
      a{
        color:inherit
      }
      a:hover{
        color:inherit;
        text-decoration: none;
      }
      /*
      .section-title:after {
          content:' ';display:block;margin:0 auto;width:100px;margin-top: 6px;border:2px solid #d0d0d0;border-radius:4px;
          -webkit-border-radius:4px;
          -moz-border-radius:4px;
          box-shadow:inset 0 1px 1px rgba(0, 0, 0, .05);
          -webkit-box-shadow:inset 0 1px 1px rgba(0, 0, 0, .05);
          -moz-box-shadow:inset 0 1px 1px rgba(0, 0, 0, .05);
          margin-bottom:1em;
        }
        */
        .att{
          padding-right: 150px;
        }
        .lgn{
          padding-right: 80px;
        }
    </style>





      {% comment %} <div class="row">
     
       

           <div class="col-md-3">
          <a href="{%url 'list-employees' %}"><img src="{% static 'recognition/img/register.png' %}" class="img-responsive" style="width:300px;height:300px ;" /></a>
          <h4 class="text-center att">Manage employee</h4>
        </div>
          {% comment %} <div class="col-md-3">
          <a href="{%url 'choose-employee'%}"><img src="{% static 'recognition/img/addphotos.png' %}" class="img-responsive" style="width:300px;height:300px ;" /></a>
          
        </div> {% endcomment %}
           {% comment %} <div class="col-md-3">
          <a href="{%url 'train' %}" id="train" ><img src="{% static 'recognition/img/train.jpeg' %}" class="img-responsive" style="width:300px;height:300px ;" /></a>
          <h4 class="text-center att">Train</h4>
        </div> 
        <div class="col-md-3">
          <a href="{%url 'view-statitics-home' %}"><img src="{% static 'recognition/img/reports.png' %}" class="img-responsive" style="width:300px;height:300px"/></a>
           <h4 class="text-center lgn">View Statitics Reports </h4>
        </div>
       




      </div>  {% endcomment %}
  <div class="row">

  

        <div class="col md-3">
   <h4 class="text-center att">Manage employee</h4>
   <a href="{%url 'list-employees' %}"><img src="{% static 'recognition/img/register.png' %}" class="img-responsive" style="width:300px;height:300px ;" /></a>
        </div>
        {% comment %} <div class="col md-3">
   <h4 class="text-center att">Manage photoes</h4>
        </div> {% endcomment %}
            <div class="col md-3">
   <h4 class="text-center att">Train</h4>
   <a href="{%url 'train' %}" id="train" ><img src="{% static 'recognition/img/train.jpeg' %}" class="img-responsive" style="width:300px;height:300px ;" /></a>
        </div>
        <div class="col md-3">
             <h4 class="text-center lgn">View Statitics Reports </h4>
             <a href="{%url 'view-statitics-home' %}"><img src="{% static 'recognition/img/reports.png' %}" class="img-responsive" style="width:300px;height:300px"/></a>
        </div> 
     


</div>

 {% if messages %}
      {% for message in messages%}
      <div class="alert alert-{{message.tags}}" > {{message}}
      </div>
      {%endfor %}

    {%endif%}


</div>



<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

FingerprintRecognition/manageData/templates/list_employees.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>

	  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

   <style>
    body{
      background: url('{% static "recognition/img/bg_image.png"%}') no-repeat center center fixed;
      background-size: cover;
      
    }
   
   </style>


	
</head>
<body>

<div class="col-lg-12" style="background: rgba(0,0,0,0.6);max-height: 20px ; padding-top:1em;padding-bottom:3em;color:#fff;border-radius:10px;-webkit-box-shadow: 2px 2px 15px 0px rgba(0, 3, 0, 0.7);
-moz-box-shadow:    2px 2px 15px 0px rgba(0, 3, 0, 0.7);
box-shadow:         2px 2px 15px 0px rgba(0, 3, 0, 0.7); margin-left:auto; margin-right: auto; ">

  <a href="{% url 'dashboard' %}"><h5 class="text-left">  Back</h5></a>
</div>
<nav class="navbar navbar-expand-lg" style="width:300px; margin-left:125px">
    <a href="{% url 'register' %}"><h5 class="btn btn-outline-light">  Register A New Employee</h5></a>
  </nav>
 <div class="col-lg-10" style="background: rgba(0,0,0,0.6);margin-top:50px ; padding-top:1em;padding-bottom:3em;color:#fff;border-radius:10px;-webkit-box-shadow: 2px 2px 15px 0px rgba(0, 3, 0, 0.7);
-moz-box-shadow:    2px 2px 15px 0px rgba(0, 3, 0, 0.7);
box-shadow:         2px 2px 15px 0px rgba(0, 3, 0, 0.7); margin-left:auto; margin-right: auto; ">




<table class = 'table table-striped table-hover'>
    <tr>
        <td><strong>ID </strong></td>
        <td><strong>Name </strong></td>
        <td><strong>Date Of Birth</strong> </td>
        <td><strong>Number of Samples</strong></td>
        <td><strong>Manage</strong></td>
    </tr>
{% for employee in employee_list%}
    {% comment %} <strong>{{employee}} </strong> {% endcomment %}
    <tr>
        <td>{{employee.id}}  </td>
        <td>{{employee.name}}  </td>
        <td>{{employee.dob}}  </td>
        <td>{{employee.sample}}  </td>
        <td align = 'right' > 
            <a href = "{% url 'update-employee' employee.id %}" class="btn btn-outline-info" > Update</a>
            <a href = "{% url 'delete-employee' employee.id %}" class="btn btn-outline-danger" > Delete</a>
        </td> 
    </tr>
{%endfor%}
</table>



  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>